//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/steve/IdeaProjects/UpsilonLang/src\UpsilonParser.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="UpsilonParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.CLSCompliant(false)]
public interface IUpsilonParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.compilation_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompilation_unit([NotNull] UpsilonParser.Compilation_unitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.namespace_or_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace_or_type_name([NotNull] UpsilonParser.Namespace_or_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.type_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_([NotNull] UpsilonParser.Type_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.base_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBase_type([NotNull] UpsilonParser.Base_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.tuple_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTuple_type([NotNull] UpsilonParser.Tuple_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.tuple_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTuple_element([NotNull] UpsilonParser.Tuple_elementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.simple_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_type([NotNull] UpsilonParser.Simple_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.numeric_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumeric_type([NotNull] UpsilonParser.Numeric_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.integral_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntegral_type([NotNull] UpsilonParser.Integral_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.class_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_type([NotNull] UpsilonParser.Class_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.type_argument_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_argument_list([NotNull] UpsilonParser.Type_argument_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.argument_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument_list([NotNull] UpsilonParser.Argument_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument([NotNull] UpsilonParser.ArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] UpsilonParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.non_assignment_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNon_assignment_expression([NotNull] UpsilonParser.Non_assignment_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] UpsilonParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.assignment_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment_operator([NotNull] UpsilonParser.Assignment_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.conditional_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditional_expression([NotNull] UpsilonParser.Conditional_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.null_coalescing_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNull_coalescing_expression([NotNull] UpsilonParser.Null_coalescing_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.conditional_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditional_or_expression([NotNull] UpsilonParser.Conditional_or_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.conditional_and_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditional_and_expression([NotNull] UpsilonParser.Conditional_and_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.inclusive_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInclusive_or_expression([NotNull] UpsilonParser.Inclusive_or_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.exclusive_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExclusive_or_expression([NotNull] UpsilonParser.Exclusive_or_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.and_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnd_expression([NotNull] UpsilonParser.And_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.equality_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquality_expression([NotNull] UpsilonParser.Equality_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.relational_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelational_expression([NotNull] UpsilonParser.Relational_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.shift_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShift_expression([NotNull] UpsilonParser.Shift_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.additive_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditive_expression([NotNull] UpsilonParser.Additive_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.multiplicative_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicative_expression([NotNull] UpsilonParser.Multiplicative_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.switch_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_expression([NotNull] UpsilonParser.Switch_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.switch_expression_arms"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_expression_arms([NotNull] UpsilonParser.Switch_expression_armsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.switch_expression_arm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_expression_arm([NotNull] UpsilonParser.Switch_expression_armContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.range_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRange_expression([NotNull] UpsilonParser.Range_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.unary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_expression([NotNull] UpsilonParser.Unary_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.cast_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCast_expression([NotNull] UpsilonParser.Cast_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.primary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary_expression([NotNull] UpsilonParser.Primary_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>literalExpression</c>
	/// labeled alternative in <see cref="UpsilonParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralExpression([NotNull] UpsilonParser.LiteralExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>simpleNameExpression</c>
	/// labeled alternative in <see cref="UpsilonParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleNameExpression([NotNull] UpsilonParser.SimpleNameExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>parenthesisExpressions</c>
	/// labeled alternative in <see cref="UpsilonParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesisExpressions([NotNull] UpsilonParser.ParenthesisExpressionsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>memberAccessExpression</c>
	/// labeled alternative in <see cref="UpsilonParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberAccessExpression([NotNull] UpsilonParser.MemberAccessExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>literalAccessExpression</c>
	/// labeled alternative in <see cref="UpsilonParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralAccessExpression([NotNull] UpsilonParser.LiteralAccessExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>thisReferenceExpression</c>
	/// labeled alternative in <see cref="UpsilonParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThisReferenceExpression([NotNull] UpsilonParser.ThisReferenceExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>baseAccessExpression</c>
	/// labeled alternative in <see cref="UpsilonParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseAccessExpression([NotNull] UpsilonParser.BaseAccessExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>objectCreationExpression</c>
	/// labeled alternative in <see cref="UpsilonParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectCreationExpression([NotNull] UpsilonParser.ObjectCreationExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>tupleExpression</c>
	/// labeled alternative in <see cref="UpsilonParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTupleExpression([NotNull] UpsilonParser.TupleExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>defaultValueExpression</c>
	/// labeled alternative in <see cref="UpsilonParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefaultValueExpression([NotNull] UpsilonParser.DefaultValueExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.throwable_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThrowable_expression([NotNull] UpsilonParser.Throwable_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.throw_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThrow_expression([NotNull] UpsilonParser.Throw_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.member_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_access([NotNull] UpsilonParser.Member_accessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.bracket_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBracket_expression([NotNull] UpsilonParser.Bracket_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.indexer_argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexer_argument([NotNull] UpsilonParser.Indexer_argumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.predefined_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPredefined_type([NotNull] UpsilonParser.Predefined_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.expression_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_list([NotNull] UpsilonParser.Expression_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.object_or_collection_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObject_or_collection_initializer([NotNull] UpsilonParser.Object_or_collection_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.object_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObject_initializer([NotNull] UpsilonParser.Object_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.member_initializer_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_initializer_list([NotNull] UpsilonParser.Member_initializer_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.member_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_initializer([NotNull] UpsilonParser.Member_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.initializer_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitializer_value([NotNull] UpsilonParser.Initializer_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.collection_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCollection_initializer([NotNull] UpsilonParser.Collection_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.element_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElement_initializer([NotNull] UpsilonParser.Element_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.anonymous_object_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnonymous_object_initializer([NotNull] UpsilonParser.Anonymous_object_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.member_declarator_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_declarator_list([NotNull] UpsilonParser.Member_declarator_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.member_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_declarator([NotNull] UpsilonParser.Member_declaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.unbound_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnbound_type_name([NotNull] UpsilonParser.Unbound_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.generic_dimension_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneric_dimension_specifier([NotNull] UpsilonParser.Generic_dimension_specifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.isType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIsType([NotNull] UpsilonParser.IsTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.isTypePatternArms"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIsTypePatternArms([NotNull] UpsilonParser.IsTypePatternArmsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.isTypePatternArm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIsTypePatternArm([NotNull] UpsilonParser.IsTypePatternArmContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.lambda_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambda_expression([NotNull] UpsilonParser.Lambda_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.anonymous_function_signature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnonymous_function_signature([NotNull] UpsilonParser.Anonymous_function_signatureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.explicit_anonymous_function_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplicit_anonymous_function_parameter_list([NotNull] UpsilonParser.Explicit_anonymous_function_parameter_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.explicit_anonymous_function_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplicit_anonymous_function_parameter([NotNull] UpsilonParser.Explicit_anonymous_function_parameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.implicit_anonymous_function_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImplicit_anonymous_function_parameter_list([NotNull] UpsilonParser.Implicit_anonymous_function_parameter_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.anonymous_function_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnonymous_function_body([NotNull] UpsilonParser.Anonymous_function_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] UpsilonParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.declarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarationStatement([NotNull] UpsilonParser.DeclarationStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.local_function_modifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocal_function_modifiers([NotNull] UpsilonParser.Local_function_modifiersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.local_function_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocal_function_body([NotNull] UpsilonParser.Local_function_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.labeled_Statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabeled_Statement([NotNull] UpsilonParser.Labeled_StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmbedded_statement([NotNull] UpsilonParser.Embedded_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>theEmptyStatement</c>
	/// labeled alternative in <see cref="UpsilonParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTheEmptyStatement([NotNull] UpsilonParser.TheEmptyStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expressionStatement</c>
	/// labeled alternative in <see cref="UpsilonParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionStatement([NotNull] UpsilonParser.ExpressionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ifStatement</c>
	/// labeled alternative in <see cref="UpsilonParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] UpsilonParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>switchStatement</c>
	/// labeled alternative in <see cref="UpsilonParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchStatement([NotNull] UpsilonParser.SwitchStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>whileStatement</c>
	/// labeled alternative in <see cref="UpsilonParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStatement([NotNull] UpsilonParser.WhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>doStatement</c>
	/// labeled alternative in <see cref="UpsilonParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoStatement([NotNull] UpsilonParser.DoStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>forStatement</c>
	/// labeled alternative in <see cref="UpsilonParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForStatement([NotNull] UpsilonParser.ForStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>breakStatement</c>
	/// labeled alternative in <see cref="UpsilonParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreakStatement([NotNull] UpsilonParser.BreakStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>continueStatement</c>
	/// labeled alternative in <see cref="UpsilonParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContinueStatement([NotNull] UpsilonParser.ContinueStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>returnStatement</c>
	/// labeled alternative in <see cref="UpsilonParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] UpsilonParser.ReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>throwStatement</c>
	/// labeled alternative in <see cref="UpsilonParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThrowStatement([NotNull] UpsilonParser.ThrowStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>tryStatement</c>
	/// labeled alternative in <see cref="UpsilonParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTryStatement([NotNull] UpsilonParser.TryStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>yieldStatement</c>
	/// labeled alternative in <see cref="UpsilonParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitYieldStatement([NotNull] UpsilonParser.YieldStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] UpsilonParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.local_variable_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocal_variable_declaration([NotNull] UpsilonParser.Local_variable_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.local_variable_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocal_variable_type([NotNull] UpsilonParser.Local_variable_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.local_variable_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocal_variable_declarator([NotNull] UpsilonParser.Local_variable_declaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.local_variable_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocal_variable_initializer([NotNull] UpsilonParser.Local_variable_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.local_constant_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocal_constant_declaration([NotNull] UpsilonParser.Local_constant_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.if_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_body([NotNull] UpsilonParser.If_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.switch_section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_section([NotNull] UpsilonParser.Switch_sectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.switch_label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_label([NotNull] UpsilonParser.Switch_labelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.case_guard"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_guard([NotNull] UpsilonParser.Case_guardContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.statement_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement_list([NotNull] UpsilonParser.Statement_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.for_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_initializer([NotNull] UpsilonParser.For_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.for_iterator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_iterator([NotNull] UpsilonParser.For_iteratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.catch_clauses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCatch_clauses([NotNull] UpsilonParser.Catch_clausesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.specific_catch_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpecific_catch_clause([NotNull] UpsilonParser.Specific_catch_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.general_catch_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneral_catch_clause([NotNull] UpsilonParser.General_catch_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.exception_filter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitException_filter([NotNull] UpsilonParser.Exception_filterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.namespace_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace_declaration([NotNull] UpsilonParser.Namespace_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.qualified_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualified_identifier([NotNull] UpsilonParser.Qualified_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.namespace_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace_body([NotNull] UpsilonParser.Namespace_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.extern_alias_directives"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtern_alias_directives([NotNull] UpsilonParser.Extern_alias_directivesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.extern_alias_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtern_alias_directive([NotNull] UpsilonParser.Extern_alias_directiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.using_directives"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUsing_directives([NotNull] UpsilonParser.Using_directivesContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>usingAliasDirective</c>
	/// labeled alternative in <see cref="UpsilonParser.using_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUsingAliasDirective([NotNull] UpsilonParser.UsingAliasDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>usingNamespaceDirective</c>
	/// labeled alternative in <see cref="UpsilonParser.using_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUsingNamespaceDirective([NotNull] UpsilonParser.UsingNamespaceDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>usingStaticDirective</c>
	/// labeled alternative in <see cref="UpsilonParser.using_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUsingStaticDirective([NotNull] UpsilonParser.UsingStaticDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.namespace_member_declarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace_member_declarations([NotNull] UpsilonParser.Namespace_member_declarationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.namespace_member_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace_member_declaration([NotNull] UpsilonParser.Namespace_member_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.type_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_declaration([NotNull] UpsilonParser.Type_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.qualified_alias_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualified_alias_member([NotNull] UpsilonParser.Qualified_alias_memberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.type_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_parameter_list([NotNull] UpsilonParser.Type_parameter_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.type_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_parameter([NotNull] UpsilonParser.Type_parameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.class_base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_base([NotNull] UpsilonParser.Class_baseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.interface_type_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_type_list([NotNull] UpsilonParser.Interface_type_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.type_parameter_constraints_clauses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_parameter_constraints_clauses([NotNull] UpsilonParser.Type_parameter_constraints_clausesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.type_parameter_constraints_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_parameter_constraints_clause([NotNull] UpsilonParser.Type_parameter_constraints_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.type_parameter_constraints"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_parameter_constraints([NotNull] UpsilonParser.Type_parameter_constraintsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.primary_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary_constraint([NotNull] UpsilonParser.Primary_constraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.secondary_constraints"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSecondary_constraints([NotNull] UpsilonParser.Secondary_constraintsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.constructor_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstructor_constraint([NotNull] UpsilonParser.Constructor_constraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.class_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_body([NotNull] UpsilonParser.Class_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.class_member_declarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_member_declarations([NotNull] UpsilonParser.Class_member_declarationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.class_member_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_member_declaration([NotNull] UpsilonParser.Class_member_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.all_member_modifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAll_member_modifiers([NotNull] UpsilonParser.All_member_modifiersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.all_member_modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAll_member_modifier([NotNull] UpsilonParser.All_member_modifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.common_member_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommon_member_declaration([NotNull] UpsilonParser.Common_member_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.typed_member_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTyped_member_declaration([NotNull] UpsilonParser.Typed_member_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.constant_declarators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant_declarators([NotNull] UpsilonParser.Constant_declaratorsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.constant_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant_declarator([NotNull] UpsilonParser.Constant_declaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.variable_declarators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_declarators([NotNull] UpsilonParser.Variable_declaratorsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.variable_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_declarator([NotNull] UpsilonParser.Variable_declaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.variable_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_initializer([NotNull] UpsilonParser.Variable_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.return_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn_type([NotNull] UpsilonParser.Return_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.member_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_name([NotNull] UpsilonParser.Member_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.method_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_body([NotNull] UpsilonParser.Method_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.formal_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormal_parameter_list([NotNull] UpsilonParser.Formal_parameter_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.fixed_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFixed_parameters([NotNull] UpsilonParser.Fixed_parametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.fixed_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFixed_parameter([NotNull] UpsilonParser.Fixed_parameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.parameter_modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter_modifier([NotNull] UpsilonParser.Parameter_modifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.parameter_array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter_array([NotNull] UpsilonParser.Parameter_arrayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.overloadable_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOverloadable_operator([NotNull] UpsilonParser.Overloadable_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.constructor_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstructor_initializer([NotNull] UpsilonParser.Constructor_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody([NotNull] UpsilonParser.BodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.array_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_type([NotNull] UpsilonParser.Array_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.rank_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRank_specifier([NotNull] UpsilonParser.Rank_specifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.array_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_initializer([NotNull] UpsilonParser.Array_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.variant_type_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariant_type_parameter_list([NotNull] UpsilonParser.Variant_type_parameter_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.variant_type_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariant_type_parameter([NotNull] UpsilonParser.Variant_type_parameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.enum_base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_base([NotNull] UpsilonParser.Enum_baseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.enum_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_body([NotNull] UpsilonParser.Enum_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.enum_member_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_member_declaration([NotNull] UpsilonParser.Enum_member_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.global_attribute_section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobal_attribute_section([NotNull] UpsilonParser.Global_attribute_sectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.global_attribute_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobal_attribute_target([NotNull] UpsilonParser.Global_attribute_targetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.attributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributes([NotNull] UpsilonParser.AttributesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.attribute_section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute_section([NotNull] UpsilonParser.Attribute_sectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.attribute_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute_target([NotNull] UpsilonParser.Attribute_targetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.attribute_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute_list([NotNull] UpsilonParser.Attribute_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute([NotNull] UpsilonParser.AttributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.attribute_argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute_argument([NotNull] UpsilonParser.Attribute_argumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.right_arrow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRight_arrow([NotNull] UpsilonParser.Right_arrowContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.right_shift"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRight_shift([NotNull] UpsilonParser.Right_shiftContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.right_shift_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRight_shift_assignment([NotNull] UpsilonParser.Right_shift_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] UpsilonParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.boolean_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolean_literal([NotNull] UpsilonParser.Boolean_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.string_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_literal([NotNull] UpsilonParser.String_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.interpolated_regular_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterpolated_regular_string([NotNull] UpsilonParser.Interpolated_regular_stringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.interpolated_verbatium_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterpolated_verbatium_string([NotNull] UpsilonParser.Interpolated_verbatium_stringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.interpolated_regular_string_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterpolated_regular_string_part([NotNull] UpsilonParser.Interpolated_regular_string_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.interpolated_verbatium_string_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterpolated_verbatium_string_part([NotNull] UpsilonParser.Interpolated_verbatium_string_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.interpolated_string_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterpolated_string_expression([NotNull] UpsilonParser.Interpolated_string_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeyword([NotNull] UpsilonParser.KeywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.class_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_definition([NotNull] UpsilonParser.Class_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.enum_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_definition([NotNull] UpsilonParser.Enum_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.function_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_definition([NotNull] UpsilonParser.Function_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.field_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitField_declaration([NotNull] UpsilonParser.Field_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.constant_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant_declaration([NotNull] UpsilonParser.Constant_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.destructor_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDestructor_definition([NotNull] UpsilonParser.Destructor_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.constructor_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstructor_declaration([NotNull] UpsilonParser.Constructor_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.method_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_declaration([NotNull] UpsilonParser.Method_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.method_member_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_member_name([NotNull] UpsilonParser.Method_member_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.arg_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArg_declaration([NotNull] UpsilonParser.Arg_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.method_invocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_invocation([NotNull] UpsilonParser.Method_invocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.object_creation_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObject_creation_expression([NotNull] UpsilonParser.Object_creation_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UpsilonParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] UpsilonParser.IdentifierContext context);
}
